### ISSUE TITLE
301/302 sometimes tagged as dead links

### ISSUE THREAD

**Issue by thecodester** [tcort/link-check#12]
I'm using the link checker, and its great, but sometimes there are 301/302 codes (redirects) that eventually get shown as broken links with status code 0, but they are good links eventually. Is there anything to do here? Lengthen timeout? 

Strange thing is that any given 301/302 link may show up in one run as broken, and in another not broken.

**Comment by tcort** [comment]
It isn't clear to me what `they are good links eventually` means. Also, the result object has an `err` property with any error that came about during the check; that should let you know what happened. You can trying increasing the timeout, it default's to `10s`. Redirects are followed but not indefinitely (if there are a lot of redirects in a row, it stops at 8). Without the links for me to examine myself or any error information, there's not much more I can do.
