### ISSUE TITLE
Support `file:` protocol

### ISSUE THREAD

**Issue by mikz** [tcort/link-check#2]
I'm trying to use [markdown-link-check](https://github.com/tcort/markdown-link-check) to verify a bunch of documentation files. Some of them contain relative links.

To make the check work locally, I need to resolve those links locally. And for that I'd like to use the `file` protocol. 

By setting `baseUrl` to `file:///some/path` the `linkCheck` function could resolve the correct path and  use `fs.readFile` instead of `request` to verify the content is there.

If I implement this, could you do releases of everything to make it work with the `markdown-lint-check` ?

**Comment by tcort** [comment]
`file:` protocol support added and released in version `4.0.0` of `link-check`. I'll bump `markdown-link-check` ASAP.
