### ISSUE TITLE
Replace deprecated "request" library

### ISSUE THREAD

**Issue by NicolasMassart** [tcort/link-check#29]
[Request is deprecated and will never be updated or fixed](https://github.com/request/request/issues/3142).
Migrating to a [new supported library](https://github.com/request/request/issues/3143) is required for long term.

Does anyone have thoughts on which one we should choose?
Would the core [node.js http](https://nodejs.org/api/http.html) be enough?

Note that we only need to be able to do HEAD and GET requests. We need to be able to pass auth and any additional headers, get HTTP codes, body and response headers.

**Comment by ccsCoder** [comment]
Hi. This looks interesting.
I went through the attached issue. Have we settled on the library of choice ?
If yes, I am interested in taking this up.

**Comment by NicolasMassart** [comment]
For what I investigated, maybe node's default http api could be enough. We only do head or get requests with a few headers, and we don't process the response body.
In the [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) spirit I would be tempted to start with this, simple.
If we need to implement more complex things later, we'll see but there's no need to load the project with a complex dependency if we only use 1% of it.
Let me know if that's something you would agree, if not, feel free to propose something and explain your choice.

**Comment by nschonni** [comment]
The case for using a library is that it will also handle proxies, which are likely a common need for a library like this that is used a lot in CI setups

**Comment by ccsCoder** [comment]
Sorry guys. Official workload increased. unassigning myself

**Comment by NicolasMassart** [comment]
@nschonni do we currently handle proxies?
@ccsCoder 😢 take care, come back whenever you can.

**Comment by nschonni** [comment]
`request` handles it under the hood already https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

**Comment by NicolasMassart** [comment]
What lib would you suggest?

**Comment by tcort** [comment]
The built-in module would be ideal, but if it doesn’t have the features
people are looking for (e.g. good proxy support), then maybe try “needle”.
I’ve had a positive experience with “make-fetch-happen” as well.

**Comment by NicolasMassart** [comment]
Migration from request to Needle also seems very easy.

**Comment by ThunderSon** [comment]
I am not the best person in node dev, but if no one is working on this, I can try building something up.
I never used needle (used axios and request), but I don't mind trying this out.

Let me know if I can be of help.

**Comment by NicolasMassart** [comment]
You are very welcome to help! I assign issue this to you and move it to "in progress".

**Comment by ThunderSon** [comment]
Should I be using promises, or traditional callbacks?
If you want we can have this staged. 
First we go with callbacks to ensure smooth migration, then we implement promises if it's something that benefits the project.

**Comment by NicolasMassart** [comment]
I agree with callback first for compatibility and then promises. That seems the wise choice.

**Comment by NicolasMassart** [comment]
hi @ThunderSon did you already start working on this?
If not, I have something that works with Needle and that helps solving another issue.
I will tell you when I have a PR ready.
