### ISSUE TITLE
TLS Checks

### ISSUE THREAD

**Issue by ThunderSon** [tcort/link-check#30]
I noticed in the code that `strictSSL: false` is set for the requests.

I understand this might be good for people that don't care about security, can we maybe have an option to set this, or have it by default and people can disable it?
In my project I'd like the checks to be :100: true and successful, and broken TLS websites aren't really that.

It would actually help the security community spread more awareness on TLS and ensuring that it stays with a valid certificate :blush:

**Comment by tcort** [comment]
I agree. I can't see a reason why we would ever want to report a link as being good if the TLS checks fail. It's something that needs attention.

I've removed the hard coded `rejectUnauthorized:false`. I'll roll it out in the next version in a few days.
