### ISSUE TITLE
Encoded URL with an id name returns 400

### ISSUE THREAD

**Issue by gaurav-nelson** [tcort/link-check#40]
@NicolasMassart Looks like a bug. 

For the URL https://en.wikipedia.org/wiki/Modern_C%2B%2B_Design#Policy-based_design `link-check  v4.5.4 and v4.5.3 gives 
```
https://en.wikipedia.org/wiki/Modern_C%2B%2B_Design#Policy-based_design is dead
```

but version `v4.5.2` gives 
```
https://en.wikipedia.org/wiki/Modern_C%2B%2B_Design#Policy-based_design is alive
```

https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/96

**Comment by NicolasMassart** [comment]
@gaurav-nelson could you give me your opinion on this fix please?
I spent time to try to understand all the URL encoding, differences between encodeURI and encodeURIComponent, node URL object (the one we use is deprecated by the way, but will be another PR),... advice don't dig here, it's a rabbit hole 🤣

**Comment by gaurav-nelson** [comment]
Thanks @NicolasMassart Based on the logic it seems right to me. I guess till we get more edge cases, this should work fine.
