### ISSUE TITLE
Replace deprecated URL usage in file protocol code

### ISSUE THREAD

**Issue by NicolasMassart** [tcort/link-check#44]
Replace legacy URL use https://nodejs.org/api/url.html#url_legacy_url_api by the new WHATWG API https://nodejs.org/api/url.html#url_the_whatwg_url_api

Current issue I found in replacing is that new URL doesn't enable to parse URLs that the old parse function was able to. Protocol has to be included.
Also we pass the link as string everywhere and it would probably be better to have it parsed as an URL as soon as possible and pass it. But it breaks the current API and would require a breaking change and main version upgrade.

**Comment by tcort** [comment]
I've updated `lib/proto/file.js` to use the WHATWG URL API. The existing test suite passes.
