### ISSUE TITLE
Some sites don't like the user agent string we hardcoded

### ISSUE THREAD

**Issue by NicolasMassart** [tcort/link-check#46]
For instance as indicated in tcort/markdown-link-check#159 `https://developer.android.com/reference/android/support/design/widget/TabItem.html` returns an error about redirect loop.

However, when calling the URL with base methods without options it works. I tried head, get, and even changed libs to Needle or Axios and it works without any issue.

But as soon as I put back the user-agent string `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36` it returns a 302 in an infinite loop.

The very strange thing about this is that as soon as there's a known browser name in the agent string, the developer.android.com site returns a 302 otherwise it return 200 as expected.
I tried with just 'chrome' and had a 302, but 'foobar' returns a 200.

So of course there's no way we can handle all the strange things developers put in their websites. I don't even know what it is supposed to check here.

It would then require to be able to set the user-agent string in some configuration.
It should be configurable by url or with a regex IMO.

NOTE: However, it's also linked to the fact that most of the config would be nice to be accessible from embedding products as proposed in [another issue](https://github.com/tcort/markdown-link-check/issues/124#issuecomment-714443230). For instance we have markdown-link-checker that "hides" the use of link-check to the users, but still users want to be able to configure things, so we usually need add the config to MLC and pass it to ML... would be far more interesting as @cadeef indicated that we don't have to relay the parameters.

**Comment by tcort** [comment]
I think to be better network citizens, the module should report it's own user agent string... e.g. `link-check/1.2.3`

I'll implement this and also provide an option to override the user agent.
