### ISSUE TITLE
False negative on ko-fi.com

### ISSUE THREAD

**Issue by undergroundwires** [tcort/link-check#47]
The ko-fi.com urls (e.g. https://ko-fi.com/undergroundwires) is marked as dead URL that is alive

**Comment by tcort** [comment]
This is an issue with `ko-fi.com` and not `link-check`. Specifically, `ko-fi.com` is behind a proxy service (cloudflare). cloudflare does some analysis on incoming request and decides how it is going to handle the request. In this case, it is responding with `403 Forbidden`. There is nothing I can do to fix this. The proxy service needs to be configured to not forbid the request link-check makes.

**Comment by undergroundwires** [comment]
@tcort I see. Thank you for your time and explaining it.
