### ISSUE TITLE
Response code `200` represents as "dead"

### ISSUE THREAD

**Issue by chris-dura** [tcort/link-check#50]
I'm seeing some cross-links to Abstract and Figma documentation URLs represent as "dead" by `link-check`, but when I inspect in my dev tools, I get a `200` response.

```js
const linkCheck = require('link-check');

linkCheck('https://help.abstract.com/hc/en-us/sections/360012262052-Collaborate-in-projects', function (err, result) {
	if (err) {
		console.error(err);
		return;
	}
	console.log(`${result.link} is ${result.status}`);
});
```

Test URLs:

- https://help.abstract.com/hc/en-us/categories/360005436612-Branches
- https://help.abstract.com/hc/en-us/sections/360012262012-Commits
- https://help.abstract.com/hc/en-us/sections/360012262032-Merge-your-work
- https://help.abstract.com/hc/en-us/sections/360012262052-Collaborate-in-projects
- https://help.figma.com/hc/en-us/articles/360039823654-Download-the-Figma-desktop-app

Could be possibly related to the sites not liking the user-agent?
https://github.com/tcort/link-check/issues/46

**Comment by tcort** [comment]
`result.statusCode` is 403, so that's why it's reported as dead.

**Comment by chris-dura** [comment]
> `result.statusCode` is 403, so that's why it's reported as dead.

It's been so long some of the URLs have changed, but they resolve in the browser, even though `result.statusCode` is 403... 

- https://help.abstract.com/hc/en-us/sections/360012262052-Collaborate-in-projects

... I suppose that's what I'm asking... if I use my Chrome browser to just go to the page, I get a status code of `200`, but `link-check` is getting `403`.

Maybe there's nothing you can do about it, but I'm guessing based on other discussions, that the UA that `link-check` provides is getting blocked by Abstract's server as `403: Forbidden`.

**Comment by nschonni** [comment]
https://github.com/tcort/link-check/issues/47#issuecomment-847764254
