### ISSUE TITLE
Hangs on bad domains

### ISSUE THREAD

**Issue by davidtheclark** [tcort/link-check#8]
If I have a typo in a domain, e.g. `https://githuuuub.com/tcort/link-check`, the tools seems to hang indefinitely.

I'm not sure what the best way is to solve this ... here are two ideas, though:
- Use [is-public-domain](https://www.npmjs.com/package/is-public-domain) to check if the domain is a public domain; if not, reject it.
- Set a timeout and cancel the request if it's exceeded.

What do you think?

**Comment by tcort** [comment]
I added a test case to the test suite using the URL provided in the issue. It doesn't cause a hang for me on node v4.4.7 nor node v8.1.3 on Mac OS X. I immediately get a dead link result with a `getaddrinfo ENOTFOUND` error attached.

I do see that I don't have a timeout set for the request. For HTTP/HTTPS, it tries a `HEAD` first, if that doesn't succeed, it tries a `GET`. Depending on a lot of variables this could lead to a 4 minute wait for one bad URL. Something needs to be done about that, so I'll leave this issue open until I implement a configurable timeout with a reasonable default to fix that.

**Comment by tcort** [comment]
If you provide more information about your setup, I can try to reproduce the issue you encountered... operating system, version of node, etc.

**Comment by davidtheclark** [comment]
🤔 I just cloned the repo, did a fresh install, and ran `npm test`. I got two failing tests, including the new one for bad domains. 

I'm on macOS and Node v6.11.0. 

Here's the full results:

```
link-check
    ✓ should find that a valid link is alive (65ms)
    ✓ should find that a valid relative link is alive
    ✓ should find that an invalid link is dead
    ✓ should find that an invalid relative link is dead
    1) should report no DNS entry as a dead link
    ✓ should try GET if HEAD fails
    ✓ should handle redirects
    ✓ should handle valid mailto
    ✓ should handle invalid mailto
    ✓ should handle file protocol
    ✓ should handle file protocol and invalid files
    ✓ should ignore file protocol on absolute links
    ✓ should ignore file protocol on fragment links
    ✓ should callback with an error on unsupported protocol
    ✓ should handle redirect loops (109ms)
    2) should handle bad domains


  14 passing (3s)
  2 failing

  1) link-check should report no DNS entry as a dead link:
     Uncaught Error: expected 'alive' to equal 'dead'
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Assertion.(anonymous function) [as be] (node_modules/expect.js/index.js:69:24)
      at test/link-check.test.js:92:38
      at Request._callback (lib/proto/http.js:28:17)
      at Request.self.callback (node_modules/request/request.js:188:22)
      at Request.<anonymous> (node_modules/request/request.js:1171:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1091:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  2) link-check should handle bad domains:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by tcort** [comment]
That's interesting, it's saying `http://example.example.example.com/` is `alive` for you.

Are you on some sort of captive network or have an ISP that serves pages for non-existent domains? If you go to [http://example.example.example.com/](http://example.example.example.com/) in a browser, what do you see?

**Comment by davidtheclark** [comment]
Also noting that when I try to `curl` that URL (`https://githuuuub.com/tcort/link-check`) or visit it in the browser, it hangs for a while and times out.

**Comment by tcort** [comment]
> Also noting that when I try to curl that URL (https://githuuuub.com/tcort/link-check) or visit it in the browser, it hangs for a while and times out.

Try it without the https.

Also see what `nslookup githuuuub.com` in the console shows. For me, I get:

```
** server can't find githuuuub.com: NXDOMAIN
```

**Comment by davidtheclark** [comment]
> Are you on some sort of captive network or have an ISP that serves pages for non-existent domains? If you go to http://example.example.example.com/ in a browser, what do you see?

Yep. I see a Cox Communications "Enhanced Error Results Page" 😆 

> Try it without the https.

`githuuuub.com/tcort/link` gets me directly to the Cox Communications "Enhanced Error Results Page", without any delay.

> Also see what nslookup githuuuub.com in the console shows.

```
Server:		2600:8800:7982:34f0:c256:27ff:fe41:a3ed
Address:	2600:8800:7982:34f0:c256:27ff:fe41:a3ed#53

Non-authoritative answer:
Name:	githuuuub.com
Address: 92.242.140.2
```

Ooof, so looks like this comes back to the ISP.

**Comment by davidtheclark** [comment]
By changing my DNS server to Google's DNS or OpenDNS I get the tests to pass. Interesting.

**Comment by tcort** [comment]
I'm not sure that there's much I can do about a DNS server that's making up results. If you can think of anything, please let me know and re-open the issue.

I've added a configurable timeout with a default of 10 seconds.

**Comment by davidtheclark** [comment]
Yep. Thanks @tcort for helping me figure this out, and for adding the timeout.
