### ISSUE TITLE
Supply status codes to indicate "alive"

### ISSUE THREAD

**Issue by thany** [tcort/link-check#9]
It'd be nice to have a way of supplying a range of status codes to indicate the status "alive". In my particular case, I just need to check if a server is running and returning responses that don't indicate a server error (e.g. no 5xx responses). Maybe a even callback to ask the caller "yo, is this status code good for you?" :)

Might this be a good idea?

Actually the module [is-alive](https://www.npmjs.com/package/is-alive) has this, but has other problems making it not useful for me, so that's why I ended up here.

**Comment by tcort** [comment]
Seems reasonable. Though I think having the caller supply a callback is overkill. I'm going to add an option to allow the caller to supply a list of status codes and/or regular expressions for matching status codes so that it is possible to specify individual codes and/or ranges.

**Comment by tcort** [comment]
Published in version `4.2.0`

**Comment by thany** [comment]
Cool :)
